### ISSUE TITLE
Should this module be deprecated?

### ISSUE THREAD

**Issue by hay** [hay/xml2json#50]
Here's a general question to all users of this library: should i deprecate it? I haven't updated this repo in years, because [xmltodict](https://github.com/martinblech/xmltodict) does roughly the same thing, but much better, reliable and faster. I'm wondering if anyone has a specific usecase for this library that other libraries don't handle (better).

I would also be open for transferring ownership of this library/repo to somebody else.

@fambon, @danielgrijalva, @grunde73, @xiuyuanjun, @marklit, @suyashjain since you've all recently added an issue and/or added a pull request, maybe you can chime in? Thanks!

**Comment by marklit** [comment]
The task I had for this involved taking the 1.5 GB compressed XML dumps from WIkipedia and converting them into one-record-per-line JSON files. The files were big enough to cause memory issues and I ended up going with [xmltodict](https://github.com/martinblech/xmltodict) instead. I documented my steps in this [blog post](https://tech.marksblogg.com/working-with-data-feeds.html).

It might be worth considering adjusting this project to handle multi-gigabyte XML files as this library came up first in my searches and seems well-rounded otherwise. Failing that, it would be good to see your engineering efforts combined with xmltodict as I'm sure there is room for improvement there as well and if that would be the case, I'd consider deprecating this project.

**Comment by hay** [comment]
@marklit, thanks for chiming in. I've actually done some XML parsing of Wikipedia dumps with `xmltodict` as well, and that worked fine.

**Comment by grunde73** [comment]
Hi,
It is not critical for me that this library is maintained. But for anyone
who want to understand the process of parsing xml it is a supernice (and
readable) little library. So please don't kill it entirely.

**Comment by hay** [comment]
@grunde73 i wasn't planning on deleting the repo, just 'archiving' it so it becomes read-only and putting up a deprecation notice. That of course wouldn't prevent you from still reading the code.
